import { AdSpace } from '@/types';

export const sampleAdSpaces: AdSpace[] = [
  {
    id: '1',
    title: 'Digital Screen at BKC',
    description: 'High-end digital billboard in Mumbai\'s business district. Perfect for corporate campaigns targeting professionals.',
    category_id: 'digital-screens',
    location_id: 'mumbai-bkc',
    publisher_id: 'pub-1',
    display_type: 'digital_screen',
    price_per_day: 83333,
    price_per_month: 2500000,
    daily_impressions: 5000,
    monthly_footfall: 150000,
    target_audience: 'Corporate Professionals',
    availability_status: 'available',
    latitude: 19.0596,
    longitude: 72.8295,
    images: [
      'https://images.pexels.com/photos/1268975/pexels-photo-1268975.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'digital-screens',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'mumbai-bkc',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Bandra Kurla Complex, Mumbai',
      latitude: 19.0596,
      longitude: 72.8295,
    }
  },
  {
    id: '2',
    title: 'MG Road Billboard',
    description: 'Prime location billboard on MG Road. High visibility during peak hours with excellent footfall.',
    category_id: 'billboard',
    location_id: 'bengaluru-mg-road',
    publisher_id: 'pub-2',
    display_type: 'static_billboard',
    price_per_day: 60000,
    price_per_month: 1800000,
    daily_impressions: 8000,
    monthly_footfall: 240000,
    target_audience: 'General Public',
    availability_status: 'available',
    latitude: 12.9716,
    longitude: 77.5946,
    images: [
      'https://images.pexels.com/photos/3566187/pexels-photo-3566187.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 3000, height: 1500 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'bengaluru-mg-road',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      address: 'MG Road, Bengaluru',
      latitude: 12.9716,
      longitude: 77.5946,
    }
  },
  {
    id: '3',
    title: 'Brigade Road Billboard',
    description: 'Strategic billboard location in Brigade Road shopping district. Ideal for retail and lifestyle brands.',
    category_id: 'billboard',
    location_id: 'bengaluru-brigade',
    publisher_id: 'pub-2',
    display_type: 'static_billboard',
    price_per_day: 40000,
    price_per_month: 1200000,
    daily_impressions: 6000,
    monthly_footfall: 180000,
    target_audience: 'Shoppers',
    availability_status: 'available',
    latitude: 12.9719,
    longitude: 77.6081,
    images: [
      'https://images.pexels.com/photos/2240763/pexels-photo-2240763.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 2400, height: 1200 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'bengaluru-brigade',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      address: 'Brigade Road, Bengaluru',
      latitude: 12.9719,
      longitude: 77.6081,
    }
  },
  {
    id: '4',
    title: 'Andheri West Billboard',
    description: 'High-traffic billboard at Andheri West junction. Perfect for mass-market campaigns.',
    category_id: 'billboard',
    location_id: 'mumbai-andheri',
    publisher_id: 'pub-1',
    display_type: 'static_billboard',
    price_per_day: 50000,
    price_per_month: 1500000,
    daily_impressions: 7000,
    monthly_footfall: 210000,
    target_audience: 'Commuters',
    availability_status: 'available',
    latitude: 19.1136,
    longitude: 72.8697,
    images: [
      'https://images.pexels.com/photos/3324591/pexels-photo-3324591.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 3000, height: 1500 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'mumbai-andheri',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Andheri West, Mumbai',
      latitude: 19.1136,
      longitude: 72.8697,
    }
  },
  {
    id: '5',
    title: 'Metro Station Digital Display',
    description: 'Digital screen at metro station entrance. High visibility during rush hours.',
    category_id: 'digital-screens',
    location_id: 'delhi-metro',
    publisher_id: 'pub-3',
    display_type: 'digital_screen',
    price_per_day: 45000,
    price_per_month: 1350000,
    daily_impressions: 10000,
    monthly_footfall: 300000,
    target_audience: 'Metro Commuters',
    availability_status: 'available',
    latitude: 28.6139,
    longitude: 77.2090,
    images: [
      'https://images.pexels.com/photos/380769/pexels-photo-380769.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'digital-screens',
      name: 'Digital Screen',
      icon_url: '',
    },
    location: {
      id: 'delhi-metro',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      address: 'Connaught Place Metro Station, Delhi',
      latitude: 28.6139,
      longitude: 77.2090,
    }
  },
  {
    id: '6',
    title: 'Airport Terminal Billboard',
    description: 'Premium billboard at airport departure terminal. Reaches affluent travelers and business professionals.',
    category_id: 'airport',
    location_id: 'mumbai-airport',
    publisher_id: 'pub-1',
    display_type: 'static_billboard',
    price_per_day: 100000,
    price_per_month: 3000000,
    daily_impressions: 15000,
    monthly_footfall: 450000,
    target_audience: 'Travelers & Business Professionals',
    availability_status: 'available',
    latitude: 19.0896,
    longitude: 72.8656,
    images: [
      'https://images.pexels.com/photos/2007401/pexels-photo-2007401.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 4000, height: 2000 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'airport',
      name: 'Airport',
      icon_url: '',
    },
    location: {
      id: 'mumbai-airport',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Chhatrapati Shivaji Maharaj International Airport, Mumbai',
      latitude: 19.0896,
      longitude: 72.8656,
    }
  },
  {
    id: '7',
    title: 'Shopping Mall LED Display',
    description: 'Large LED display at main entrance of premium shopping mall. Perfect for retail campaigns.',
    category_id: 'digital-screens',
    location_id: 'mumbai-mall',
    publisher_id: 'pub-1',
    display_type: 'led_display',
    price_per_day: 55000,
    price_per_month: 1650000,
    daily_impressions: 12000,
    monthly_footfall: 360000,
    target_audience: 'Shoppers & Families',
    availability_status: 'available',
    latitude: 19.1176,
    longitude: 72.9060,
    images: [
      'https://images.pexels.com/photos/1797428/pexels-photo-1797428.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'digital-screens',
      name: 'Digital Screen',
      icon_url: '',
    },
    location: {
      id: 'mumbai-mall',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Phoenix Marketcity, Kurla, Mumbai',
      latitude: 19.1176,
      longitude: 72.9060,
    }
  },
  {
    id: '8',
    title: 'Bus Station Billboard',
    description: 'Billboard at major bus terminus. High visibility and excellent reach for local campaigns.',
    category_id: 'bus-station',
    location_id: 'pune-bus',
    publisher_id: 'pub-4',
    display_type: 'static_billboard',
    price_per_day: 25000,
    price_per_month: 750000,
    daily_impressions: 4000,
    monthly_footfall: 120000,
    target_audience: 'Daily Commuters',
    availability_status: 'available',
    latitude: 18.5204,
    longitude: 73.8567,
    images: [
      'https://images.pexels.com/photos/1116442/pexels-photo-1116442.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 2400, height: 1200 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'bus-station',
      name: 'Bus Station',
      icon_url: '',
    },
    location: {
      id: 'pune-bus',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      address: 'Pune Railway Station Bus Stand',
      latitude: 18.5204,
      longitude: 73.8567,
    }
  },
  {
    id: '9',
    title: 'Times Square Style LED Wall',
    description: 'Massive LED wall in city center. Premium advertising location with maximum visibility.',
    category_id: 'digital-screens',
    location_id: 'mumbai-center',
    publisher_id: 'pub-1',
    display_type: 'led_display',
    price_per_day: 150000,
    price_per_month: 4500000,
    daily_impressions: 20000,
    monthly_footfall: 600000,
    target_audience: 'Mass Audience',
    availability_status: 'available',
    latitude: 18.9388,
    longitude: 72.8354,
    images: [
      'https://images.pexels.com/photos/2469122/pexels-photo-2469122.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 5000, height: 3000 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'digital-screens',
      name: 'LED Display',
      icon_url: '',
    },
    location: {
      id: 'mumbai-center',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Dadar, Mumbai',
      latitude: 18.9388,
      longitude: 72.8354,
    }
  },
  {
    id: '10',
    title: 'Highway Billboard - Mumbai-Pune',
    description: 'Large billboard on Mumbai-Pune expressway. Excellent for automobile and travel campaigns.',
    category_id: 'billboard',
    location_id: 'highway-mumbai',
    publisher_id: 'pub-1',
    display_type: 'static_billboard',
    price_per_day: 35000,
    price_per_month: 1050000,
    daily_impressions: 5000,
    monthly_footfall: 150000,
    target_audience: 'Highway Travelers',
    availability_status: 'available',
    latitude: 19.0330,
    longitude: 73.0297,
    images: [
      'https://images.pexels.com/photos/1058277/pexels-photo-1058277.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 3600, height: 1800 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'highway-mumbai',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Mumbai-Pune Expressway',
      latitude: 19.0330,
      longitude: 73.0297,
    }
  },
  {
    id: '11',
    title: 'Cinema Hall Advertising',
    description: 'Digital screen advertising in multiplex cinema. Captive audience during movie intervals.',
    category_id: 'cinema',
    location_id: 'mumbai-cinema',
    publisher_id: 'pub-1',
    display_type: 'digital_screen',
    price_per_day: 30000,
    price_per_month: 900000,
    daily_impressions: 3000,
    monthly_footfall: 90000,
    target_audience: 'Movie Goers',
    availability_status: 'available',
    latitude: 19.0728,
    longitude: 72.8826,
    images: [
      'https://images.pexels.com/photos/7991158/pexels-photo-7991158.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'cinema',
      name: 'Cinema Screens',
      icon_url: '',
    },
    location: {
      id: 'mumbai-cinema',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'PVR INOX, Juhu, Mumbai',
      latitude: 19.0728,
      longitude: 72.8826,
    }
  },
  {
    id: '12',
    title: 'City Mall Digital Billboard',
    description: 'Premium digital billboard at city\'s busiest shopping mall. High footfall and engagement.',
    category_id: 'billboard',
    location_id: 'delhi-mall',
    publisher_id: 'pub-3',
    display_type: 'digital_screen',
    price_per_day: 70000,
    price_per_month: 2100000,
    daily_impressions: 9000,
    monthly_footfall: 270000,
    target_audience: 'Urban Shoppers',
    availability_status: 'available',
    latitude: 28.5494,
    longitude: 77.2501,
    images: [
      'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'delhi-mall',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      address: 'Select Citywalk Mall, Saket, Delhi',
      latitude: 28.5494,
      longitude: 77.2501,
    }
  },
  // Chennai ad spaces
  {
    id: '13',
    title: 'T Nagar Digital Billboard',
    description: 'High-traffic digital billboard in T Nagar shopping district. Perfect for retail brands.',
    category_id: 'billboard',
    location_id: 'chennai-tnagar',
    publisher_id: 'pub-5',
    display_type: 'digital_screen',
    price_per_day: 55000,
    price_per_month: 1650000,
    daily_impressions: 7500,
    monthly_footfall: 225000,
    target_audience: 'Shoppers',
    availability_status: 'available',
    latitude: 13.0418,
    longitude: 80.2341,
    images: [
      'https://images.pexels.com/photos/1509428/pexels-photo-1509428.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'chennai-tnagar',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      address: 'T Nagar, Chennai',
      latitude: 13.0418,
      longitude: 80.2341,
    }
  },
  {
    id: '14',
    title: 'Chennai Airport Billboard',
    description: 'Premium billboard at Chennai International Airport. Reaches business travelers and tourists.',
    category_id: 'airport',
    location_id: 'chennai-airport',
    publisher_id: 'pub-5',
    display_type: 'static_billboard',
    price_per_day: 85000,
    price_per_month: 2550000,
    daily_impressions: 12000,
    monthly_footfall: 360000,
    target_audience: 'Travelers',
    availability_status: 'available',
    latitude: 12.9941,
    longitude: 80.1709,
    images: [
      'https://images.pexels.com/photos/723240/pexels-photo-723240.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 3600, height: 1800 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'airport',
      name: 'Airport',
      icon_url: '',
    },
    location: {
      id: 'chennai-airport',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      address: 'Chennai International Airport',
      latitude: 12.9941,
      longitude: 80.1709,
    }
  },
  {
    id: '15',
    title: 'Marina Beach Billboard',
    description: 'Iconic location on Marina Beach road. Excellent visibility for lifestyle and entertainment brands.',
    category_id: 'billboard',
    location_id: 'chennai-marina',
    publisher_id: 'pub-5',
    display_type: 'static_billboard',
    price_per_day: 48000,
    price_per_month: 1440000,
    daily_impressions: 8000,
    monthly_footfall: 240000,
    target_audience: 'Tourists & Locals',
    availability_status: 'available',
    latitude: 13.0499,
    longitude: 80.2824,
    images: [
      'https://images.pexels.com/photos/3585089/pexels-photo-3585089.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 3000, height: 1500 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'chennai-marina',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      address: 'Marina Beach Road, Chennai',
      latitude: 13.0499,
      longitude: 80.2824,
    }
  },
  // Kolkata ad spaces
  {
    id: '16',
    title: 'Park Street Digital Screen',
    description: 'Prime digital screen on Park Street. High footfall area with excellent brand visibility.',
    category_id: 'digital-screens',
    location_id: 'kolkata-park',
    publisher_id: 'pub-6',
    display_type: 'digital_screen',
    price_per_day: 42000,
    price_per_month: 1260000,
    daily_impressions: 6500,
    monthly_footfall: 195000,
    target_audience: 'Urban Professionals',
    availability_status: 'available',
    latitude: 22.5542,
    longitude: 88.3516,
    images: [
      'https://images.pexels.com/photos/1181395/pexels-photo-1181395.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'digital-screens',
      name: 'Digital Screen',
      icon_url: '',
    },
    location: {
      id: 'kolkata-park',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
      address: 'Park Street, Kolkata',
      latitude: 22.5542,
      longitude: 88.3516,
    }
  },
  {
    id: '17',
    title: 'Kolkata Metro Station Display',
    description: 'Digital display at major metro station. High commuter traffic during peak hours.',
    category_id: 'digital-screens',
    location_id: 'kolkata-metro',
    publisher_id: 'pub-6',
    display_type: 'digital_screen',
    price_per_day: 38000,
    price_per_month: 1140000,
    daily_impressions: 9000,
    monthly_footfall: 270000,
    target_audience: 'Metro Commuters',
    availability_status: 'available',
    latitude: 22.5726,
    longitude: 88.3639,
    images: [
      'https://images.pexels.com/photos/1036804/pexels-photo-1036804.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'digital-screens',
      name: 'Digital Screen',
      icon_url: '',
    },
    location: {
      id: 'kolkata-metro',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
      address: 'Esplanade Metro Station, Kolkata',
      latitude: 22.5726,
      longitude: 88.3639,
    }
  },
  // Hyderabad ad spaces
  {
    id: '18',
    title: 'Hitech City Digital Wall',
    description: 'Massive LED wall in Hitech City IT hub. Perfect for tech and corporate campaigns.',
    category_id: 'digital-screens',
    location_id: 'hyderabad-hitech',
    publisher_id: 'pub-7',
    display_type: 'led_display',
    price_per_day: 75000,
    price_per_month: 2250000,
    daily_impressions: 11000,
    monthly_footfall: 330000,
    target_audience: 'IT Professionals',
    availability_status: 'available',
    latitude: 17.4485,
    longitude: 78.3908,
    images: [
      'https://images.pexels.com/photos/1666816/pexels-photo-1666816.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 2560, height: 1440 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'digital-screens',
      name: 'LED Display',
      icon_url: '',
    },
    location: {
      id: 'hyderabad-hitech',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      address: 'Hitech City, Hyderabad',
      latitude: 17.4485,
      longitude: 78.3908,
    }
  },
  {
    id: '19',
    title: 'Banjara Hills Billboard',
    description: 'Premium billboard in upscale Banjara Hills area. Targets affluent demographics.',
    category_id: 'billboard',
    location_id: 'hyderabad-banjara',
    publisher_id: 'pub-7',
    display_type: 'static_billboard',
    price_per_day: 52000,
    price_per_month: 1560000,
    daily_impressions: 6000,
    monthly_footfall: 180000,
    target_audience: 'Affluent Residents',
    availability_status: 'available',
    latitude: 17.4239,
    longitude: 78.4738,
    images: [
      'https://images.pexels.com/photos/2387793/pexels-photo-2387793.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 3000, height: 1500 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'hyderabad-banjara',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      address: 'Banjara Hills, Hyderabad',
      latitude: 17.4239,
      longitude: 78.4738,
    }
  },
  {
    id: '20',
    title: 'Hyderabad Airport Digital Screen',
    description: 'Digital screen at Shamshabad Airport. Premium location for business and travel campaigns.',
    category_id: 'airport',
    location_id: 'hyderabad-airport',
    publisher_id: 'pub-7',
    display_type: 'digital_screen',
    price_per_day: 90000,
    price_per_month: 2700000,
    daily_impressions: 13000,
    monthly_footfall: 390000,
    target_audience: 'Air Travelers',
    availability_status: 'available',
    latitude: 17.2403,
    longitude: 78.4294,
    images: [
      'https://images.pexels.com/photos/2026324/pexels-photo-2026324.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'airport',
      name: 'Airport',
      icon_url: '',
    },
    location: {
      id: 'hyderabad-airport',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      address: 'Rajiv Gandhi International Airport, Hyderabad',
      latitude: 17.2403,
      longitude: 78.4294,
    }
  },
  // Pune ad spaces
  {
    id: '21',
    title: 'FC Road Billboard',
    description: 'Popular billboard on Fergusson College Road. High student and youth footfall.',
    category_id: 'billboard',
    location_id: 'pune-fc',
    publisher_id: 'pub-4',
    display_type: 'static_billboard',
    price_per_day: 32000,
    price_per_month: 960000,
    daily_impressions: 5500,
    monthly_footfall: 165000,
    target_audience: 'Students & Youth',
    availability_status: 'available',
    latitude: 18.5362,
    longitude: 73.8264,
    images: [
      'https://images.pexels.com/photos/1694000/pexels-photo-1694000.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 2400, height: 1200 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'pune-fc',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      address: 'FC Road, Pune',
      latitude: 18.5362,
      longitude: 73.8264,
    }
  },
  {
    id: '22',
    title: 'Koregaon Park Digital Screen',
    description: 'Modern digital screen in upscale Koregaon Park area. Targets premium audience.',
    category_id: 'digital-screens',
    location_id: 'pune-koregaon',
    publisher_id: 'pub-4',
    display_type: 'digital_screen',
    price_per_day: 44000,
    price_per_month: 1320000,
    daily_impressions: 4500,
    monthly_footfall: 135000,
    target_audience: 'Premium Residents',
    availability_status: 'available',
    latitude: 18.5314,
    longitude: 73.8932,
    images: [
      'https://images.pexels.com/photos/2422259/pexels-photo-2422259.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'digital-screens',
      name: 'Digital Screen',
      icon_url: '',
    },
    location: {
      id: 'pune-koregaon',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      address: 'Koregaon Park, Pune',
      latitude: 18.5314,
      longitude: 73.8932,
    }
  },
  // Delhi additional spaces
  {
    id: '23',
    title: 'Rajiv Chowk Metro Billboard',
    description: 'High-traffic metro station billboard. Excellent reach to daily commuters.',
    category_id: 'digital-screens',
    location_id: 'delhi-rajiv',
    publisher_id: 'pub-3',
    display_type: 'digital_screen',
    price_per_day: 65000,
    price_per_month: 1950000,
    daily_impressions: 14000,
    monthly_footfall: 420000,
    target_audience: 'Metro Commuters',
    availability_status: 'available',
    latitude: 28.6328,
    longitude: 77.2197,
    images: [
      'https://images.pexels.com/photos/1121382/pexels-photo-1121382.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'digital-screens',
      name: 'Digital Screen',
      icon_url: '',
    },
    location: {
      id: 'delhi-rajiv',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      address: 'Rajiv Chowk Metro Station, Delhi',
      latitude: 28.6328,
      longitude: 77.2197,
    }
  },
  {
    id: '24',
    title: 'Nehru Place Digital Billboard',
    description: 'Digital billboard in IT market hub. Perfect for technology and gadget campaigns.',
    category_id: 'billboard',
    location_id: 'delhi-nehru',
    publisher_id: 'pub-3',
    display_type: 'digital_screen',
    price_per_day: 48000,
    price_per_month: 1440000,
    daily_impressions: 7000,
    monthly_footfall: 210000,
    target_audience: 'Tech Enthusiasts',
    availability_status: 'available',
    latitude: 28.5494,
    longitude: 77.2500,
    images: [
      'https://images.pexels.com/photos/1181354/pexels-photo-1181354.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1920, height: 1080 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'delhi-nehru',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      address: 'Nehru Place, Delhi',
      latitude: 28.5494,
      longitude: 77.2500,
    }
  },
  // Bengaluru additional spaces
  {
    id: '25',
    title: 'Whitefield Tech Park Billboard',
    description: 'Billboard at IT park entrance. Targets tech professionals and corporates.',
    category_id: 'billboard',
    location_id: 'bengaluru-whitefield',
    publisher_id: 'pub-2',
    display_type: 'static_billboard',
    price_per_day: 58000,
    price_per_month: 1740000,
    daily_impressions: 8500,
    monthly_footfall: 255000,
    target_audience: 'IT Professionals',
    availability_status: 'available',
    latitude: 12.9698,
    longitude: 77.7499,
    images: [
      'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 3000, height: 1500 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'bengaluru-whitefield',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      address: 'Whitefield, Bengaluru',
      latitude: 12.9698,
      longitude: 77.7499,
    }
  },
  {
    id: '26',
    title: 'Bangalore Airport Billboard',
    description: 'Premium billboard at Kempegowda International Airport. Reaches travelers and business class.',
    category_id: 'airport',
    location_id: 'bengaluru-airport',
    publisher_id: 'pub-2',
    display_type: 'static_billboard',
    price_per_day: 95000,
    price_per_month: 2850000,
    daily_impressions: 14000,
    monthly_footfall: 420000,
    target_audience: 'Air Travelers',
    availability_status: 'available',
    latitude: 13.1986,
    longitude: 77.7066,
    images: [
      'https://images.pexels.com/photos/2033343/pexels-photo-2033343.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 4000, height: 2000 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'airport',
      name: 'Airport',
      icon_url: '',
    },
    location: {
      id: 'bengaluru-airport',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      address: 'Kempegowda International Airport, Bengaluru',
      latitude: 13.1986,
      longitude: 77.7066,
    }
  },
  // Mumbai additional spaces
  {
    id: '27',
    title: 'Churchgate Station Billboard',
    description: 'Iconic location at Churchgate railway station. Massive daily commuter footfall.',
    category_id: 'bus-station',
    location_id: 'mumbai-churchgate',
    publisher_id: 'pub-1',
    display_type: 'static_billboard',
    price_per_day: 62000,
    price_per_month: 1860000,
    daily_impressions: 16000,
    monthly_footfall: 480000,
    target_audience: 'Daily Commuters',
    availability_status: 'available',
    latitude: 18.9322,
    longitude: 72.8264,
    images: [
      'https://images.pexels.com/photos/3861458/pexels-photo-3861458.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 3000, height: 1500 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'bus-station',
      name: 'Bus Station',
      icon_url: '',
    },
    location: {
      id: 'mumbai-churchgate',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Churchgate Station, Mumbai',
      latitude: 18.9322,
      longitude: 72.8264,
    }
  },
  {
    id: '28',
    title: 'Powai Lake View Billboard',
    description: 'Scenic billboard with Powai Lake backdrop. Premium location for lifestyle brands.',
    category_id: 'billboard',
    location_id: 'mumbai-powai',
    publisher_id: 'pub-1',
    display_type: 'static_billboard',
    price_per_day: 47000,
    price_per_month: 1410000,
    daily_impressions: 5500,
    monthly_footfall: 165000,
    target_audience: 'Residents & Visitors',
    availability_status: 'available',
    latitude: 19.1197,
    longitude: 72.9078,
    images: [
      'https://images.pexels.com/photos/2480072/pexels-photo-2480072.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 2400, height: 1200 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'billboard',
      name: 'Billboard',
      icon_url: '',
    },
    location: {
      id: 'mumbai-powai',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Powai, Mumbai',
      latitude: 19.1197,
      longitude: 72.9078,
    }
  },
  // Movable Ad Spaces - Auto Rickshaws
  {
    id: '29',
    title: 'Auto Rickshaw Fleet - Mumbai Central',
    description: 'Fleet of 50 auto rickshaws covering major routes in Mumbai. High visibility mobile advertising.',
    category_id: 'auto-rickshaw',
    location_id: 'mumbai-central',
    publisher_id: 'pub-1',
    display_type: 'auto_rickshaw',
    price_per_day: 15000,
    price_per_month: 450000,
    daily_impressions: 25000,
    monthly_footfall: 750000,
    target_audience: 'Local Commuters',
    availability_status: 'available',
    latitude: 18.9706,
    longitude: 72.8194,
    images: [
      'https://images.pexels.com/photos/1592384/pexels-photo-1592384.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1000, height: 500 },
    route: {
      center_location: {
        latitude: 19.0233,
        longitude: 72.8485,
        address: 'Mumbai Central Area'
      },
      coverage_radius: 5, // 5 km radius
      base_coverage_km: 5,
      additional_coverage_km: 10 // can add up to 10 more km
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'auto-rickshaw',
      name: 'Auto Rickshaw',
      icon_url: '',
    },
    location: {
      id: 'mumbai-central',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Mumbai Central to Andheri Route',
      latitude: 18.9706,
      longitude: 72.8194,
    }
  },
  {
    id: '30',
    title: 'Auto Rickshaw Fleet - Bengaluru IT Corridor',
    description: '30 auto rickshaws covering Whitefield to Electronic City route. Perfect for tech brand campaigns.',
    category_id: 'auto-rickshaw',
    location_id: 'bengaluru-it',
    publisher_id: 'pub-2',
    display_type: 'auto_rickshaw',
    price_per_day: 12000,
    price_per_month: 360000,
    daily_impressions: 18000,
    monthly_footfall: 540000,
    target_audience: 'IT Professionals',
    availability_status: 'available',
    latitude: 12.9698,
    longitude: 77.7499,
    images: [
      'https://images.pexels.com/photos/1592384/pexels-photo-1592384.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1000, height: 500 },
    route: {
      center_location: {
        latitude: 12.9077,
        longitude: 77.7066,
        address: 'IT Corridor, Bengaluru'
      },
      coverage_radius: 8, // 8 km radius
      base_coverage_km: 8,
      additional_coverage_km: 12 // can add up to 12 more km
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'auto-rickshaw',
      name: 'Auto Rickshaw',
      icon_url: '',
    },
    location: {
      id: 'bengaluru-it',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      address: 'Whitefield to Electronic City Route',
      latitude: 12.9698,
      longitude: 77.7499,
    }
  },
  // Movable Ad Spaces - Bikes
  {
    id: '31',
    title: 'Bike Fleet - Delhi Metro Routes',
    description: 'Fleet of 100 delivery bikes covering major metro station routes in Delhi. High frequency visibility.',
    category_id: 'bike',
    location_id: 'delhi-metro-bikes',
    publisher_id: 'pub-3',
    display_type: 'bike',
    price_per_day: 8000,
    price_per_month: 240000,
    daily_impressions: 30000,
    monthly_footfall: 900000,
    target_audience: 'Metro Commuters',
    availability_status: 'available',
    latitude: 28.6139,
    longitude: 77.2090,
    images: [
      'https://images.pexels.com/photos/163140/bicycle-bike-traffic-vehicle-163140.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 800, height: 400 },
    route: {
      center_location: {
        latitude: 28.6233,
        longitude: 77.2143,
        address: 'Central Delhi Metro Area'
      },
      coverage_radius: 6, // 6 km radius
      base_coverage_km: 6,
      additional_coverage_km: 8 // can add up to 8 more km
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'bike',
      name: 'Bike',
      icon_url: '',
    },
    location: {
      id: 'delhi-metro-bikes',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      address: 'CP to Rajiv Chowk Metro Route',
      latitude: 28.6139,
      longitude: 77.2090,
    }
  },
  {
    id: '32',
    title: 'Bike Fleet - Mumbai Coastal Route',
    description: '50 bikes covering Marine Drive to Bandra route. Scenic route with high tourist footfall.',
    category_id: 'bike',
    location_id: 'mumbai-coastal',
    publisher_id: 'pub-1',
    display_type: 'bike',
    price_per_day: 10000,
    price_per_month: 300000,
    daily_impressions: 20000,
    monthly_footfall: 600000,
    target_audience: 'Tourists & Locals',
    availability_status: 'available',
    latitude: 18.9388,
    longitude: 72.8354,
    images: [
      'https://images.pexels.com/photos/163140/bicycle-bike-traffic-vehicle-163140.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 800, height: 400 },
    route: {
      center_location: {
        latitude: 18.9992,
        longitude: 72.8324,
        address: 'Mumbai Coastal Area'
      },
      coverage_radius: 7, // 7 km radius
      base_coverage_km: 7,
      additional_coverage_km: 10 // can add up to 10 more km
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'bike',
      name: 'Bike',
      icon_url: '',
    },
    location: {
      id: 'mumbai-coastal',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Marine Drive to Bandra Route',
      latitude: 18.9388,
      longitude: 72.8354,
    }
  },
  // Movable Ad Spaces - Cabs
  {
    id: '33',
    title: 'Cab Fleet - Airport Shuttle Service',
    description: 'Premium cab fleet covering airport to city center routes. Targets business travelers and tourists.',
    category_id: 'cab',
    location_id: 'mumbai-airport-cabs',
    publisher_id: 'pub-1',
    display_type: 'cab',
    price_per_day: 25000,
    price_per_month: 750000,
    daily_impressions: 15000,
    monthly_footfall: 450000,
    target_audience: 'Air Travelers',
    availability_status: 'available',
    latitude: 19.0896,
    longitude: 72.8656,
    images: [
      'https://images.pexels.com/photos/164634/pexels-photo-164634.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1200, height: 600 },
    route: {
      center_location: {
        latitude: 19.0142,
        longitude: 72.8505,
        address: 'Mumbai Airport Zone'
      },
      coverage_radius: 10, // 10 km radius
      base_coverage_km: 10,
      additional_coverage_km: 15 // can add up to 15 more km
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'cab',
      name: 'Cab',
      icon_url: '',
    },
    location: {
      id: 'mumbai-airport-cabs',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      address: 'Airport to Marine Drive Route',
      latitude: 19.0896,
      longitude: 72.8656,
    }
  },
  {
    id: '34',
    title: 'Cab Fleet - Bengaluru City Routes',
    description: 'Fleet of 75 cabs covering MG Road to Indiranagar routes. Premium urban advertising.',
    category_id: 'cab',
    location_id: 'bengaluru-cabs',
    publisher_id: 'pub-2',
    display_type: 'cab',
    price_per_day: 18000,
    price_per_month: 540000,
    daily_impressions: 22000,
    monthly_footfall: 660000,
    target_audience: 'Urban Professionals',
    availability_status: 'available',
    latitude: 12.9716,
    longitude: 77.5946,
    images: [
      'https://images.pexels.com/photos/164634/pexels-photo-164634.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    dimensions: { width: 1200, height: 600 },
    route: {
      center_location: {
        latitude: 12.9750,
        longitude: 77.6177,
        address: 'Central Bengaluru'
      },
      coverage_radius: 9, // 9 km radius
      base_coverage_km: 9,
      additional_coverage_km: 12 // can add up to 12 more km
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'cab',
      name: 'Cab',
      icon_url: '',
    },
    location: {
      id: 'bengaluru-cabs',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      address: 'MG Road to Indiranagar Route',
      latitude: 12.9716,
      longitude: 77.5946,
    }
  },
];


